spring.application.name=hybrid-ai-runtime
spring.profiles.active=local

# Tat cac modality khong dung den
spring.ai.openai.embedding.enabled=false
spring.ai.openai.image.enabled=false
spring.ai.openai.audio.transcription.enabled=false
spring.ai.openai.audio.speech.enabled=false
spring.ai.openai.moderation.enabled=false
spring.ai.ollama.embedding.enabled=false
